name: Run Dev Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
            cd project_a
            npm install

      - name: Build
        run: |
          cd project_a
          DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID \
          DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET \
          EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY \
          EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY \
          GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
          GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
          DATABASE_URL \
          NEXTAUTH_SECRET \
          npm run build
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
          EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Dev Server
        run: |
          cd project_a
          npm run dev
